#!/bin/bash
# Sets up required files for running the project at boot

# create service file
cat << 'EOF' >/etc/systemd/system/reefpi_addons.service
[Unit]
Description=Reef Pi Addons Python Scripts
After=network-online.target reef-pi.service
Wants=network-online.target reef-pi.service


[Service]
Type=simple
Restart=always
RestartSec=3
ExecStart=/bin/bash -lc '/usr/local/bin/reefpi_addons.sh'

[Install]
WantedBy=multi-user.target
EOF

# Create sh script to run the python packages
cat << 'EOF' >/usr/local/bin/reefpi_addons.sh
#!/bin/bash
# This file is auto generated by reef pi addons service setup
sudo mkdir -p /var/log/reefpi_addon_logs/
reefpi_script_handler &> /var/log/reefpi_addon_logs/$(date +"%Y-%m-%dT%H-%M-%S").log
EOF

# give launcher permissions and enable at boot
chmod u+x /usr/local/bin/reefpi_addons.sh
sudo systemctl start reefpi_addons
sudo systemctl enable reefpi_addons